[[bookmark]]
key = "r"
path = "/home/wrq/refer"

[[bookmark]]
key = "c"
path = "/home/wrq/.local/share/fcitx5/pinyin"

[[bookmark]]
key = "m"
path = "/home/wrq/.config/mango"

[[bookmark]]
key = "t"
path = "/home/wrq/test"
