[default_view]

keymap = [
  { keys = ["escape"], command = "escape" },
  { keys = ["t"], command = "new_tab --current" },
  { keys = ["ctrl+q"], command = "close_tab" },
  { keys = ["q"], command = "quit" },

  { keys = ["ctrl+r"], command = "reload_dirlist" },
  { keys = ["."], command = "toggle_hidden" },
  { keys = ["alt+l"], command = "tab_switch 1" },
  { keys = ["alt+h"], command = "tab_switch -1" },


  # arrow keys
  { keys = ["arrow_up"], command = "cursor_move_up" },
  { keys = ["arrow_down"], command = "cursor_move_down" },
  { keys = ["arrow_left"], command = "cd .." },
  { keys = ["arrow_right"], command = "open" },
  { keys = ["\n"], command = "open" },
  { keys = ["b"], command = "cursor_move_home" },
  { keys = ["e"], command = "cursor_move_end" },
  { keys = ["page_up"], command = "cursor_move_page_up" },
  { keys = ["page_down"], command = "cursor_move_page_down" },


  # vim-like keybindings
  { keys = ["j"], command = "cursor_move_down" },
  { keys = ["k"], command = "cursor_move_up" },
  { keys = ["J"], command = "cursor_move_down 5" },
  { keys = ["K"], command = "cursor_move_up 5" },
  { keys = ["h"], command = "cd .." },
  { keys = ["l"], command = "open" },
  { keys = ["o"], command = "open_with" },


  { keys = ["alt+k"], command = "parent_cursor_move_up" },
  { keys = ["alt+j"], command = "parent_cursor_move_down" },

  { keys = ["g"," "], command = ":cd " },
  { keys = ["x"], command = "cut_files" },
  { keys = ["y"], command = "copy_files" },
  { keys = ["c", "f"], command = "copy_filename" },
  { keys = ["c", "n"], command = "copy_filename_without_extension" },
  { keys = ["c", "c"], command = "copy_filepath" },
  { keys = ["c", "d"], command = "copy_dirpath" },

  { keys = ["d"], command = "delete_files" },
  { keys = ["D"], command = "delete_files" },

  { keys = ["p"], command = "paste_files" },
  { keys = ["P"], command = "paste_files --overwrite=true" },

  { keys = ["r"], command = "rename_append" },
  { keys = ["R"], command = "rename_prepend" },

  { keys = ["a"], command = ":touch " },

  { keys = [" "], command = "select --toggle=true" },
  { keys = ["ctrl+a"], command = "select --all=true --toggle=true" },
  { keys = ["V"], command = "toggle_visual" },

  { keys = ["w"], command = "show_tasks --exit-key=w" },
  { keys = ["u","r"], command = "bulk_rename" },
  { keys = ["="], command = "set_mode" },

  { keys = [":"], command = ":" },
  { keys = [";"], command = ":" },

  { keys = ["'"], command = ":shell " },
  { keys = ["m", "k"], command = ":mkdir " },
  { keys = ["c", "w"], command = ":rename " },

  { keys = ["f","n"], command = ":search " },
  { keys = ["|"], command = ":search_inc " },
  { keys = ["\\"], command = ":search_glob " },
  { keys = ["f","f"], command = "search_fzf" },
  { keys = ["f","t"], command = "subdir_fzf" },

  { keys = ["n"], command = "search_next" },
  { keys = ["N"], command = "search_prev" },

  { keys = ["s", "r"], command = "sort reverse" },
  { keys = ["s", "l"], command = "sort lexical" },
  { keys = ["s", "m"], command = "sort mtime" },
  { keys = ["s", "n"], command = "sort natural" },
  { keys = ["s", "s"], command = "sort size" },
  { keys = ["s", "e"], command = "sort ext" },

  { keys = ["m", "s"], command = "linemode size" },
  { keys = ["m", "m"], command = "linemode mtime" },
  { keys = ["m", "M"], command = "linemode size" },

  { keys = ["g", "r"], command = "cd /" },
  { keys = ["g", "c"], command = "cd ~/.config" },
  { keys = ["g", "d"], command = "cd ~/down/" },
  { keys = ["g", "o"], command = "cd ~/video/" },
  { keys = ["g", "i"], command = "cd ~/Images/" },
  { keys = ["g", "h"], command = "cd ~/" },
  { keys = ["g", "k"], command = "cd ~/deskenv/master" },
  { keys = ["g", "j"], command = "cd ~/deskenv/archieve" },

  { keys = ["u", "a"], command = "add_bookmark" },
  { keys = ["u", "g"], command = "cd_bookmark" },
  { keys = ["u", "i"], command = "shell lazygit" },
  { keys = ["u", "s"], command = "shell fish" },
  { keys = ["u", "f"], command = "shell /home/wrq/tool/xqxdrag.sh %s" },
  { keys = ["u", "w"], command = "shell /home/wrq/tool/wqxdrag.sh %s" },
  { keys = ["?"], command = "help" },
]

[task_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], command = "cursor_move_up" },
  { keys = ["arrow_down"], command = "cursor_move_down" },
  { keys = ["home"], command = "cursor_move_home" },
  { keys = ["end"], command = "cursor_move_end" },

  # vim-like keybindings
  { keys = ["j"], command = "cursor_move_down" },
  { keys = ["k"], command = "cursor_move_up" },
  { keys = ["b"], command = "cursor_move_home" },
  { keys = ["e"], command = "cursor_move_end" },

  { keys = ["w"], command = "show_tasks" },
  { keys = ["escape"], command = "show_tasks" },
]

[help_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], command = "cursor_move_up" },
  { keys = ["arrow_down"], command = "cursor_move_down" },
  { keys = ["home"], command = "cursor_move_home" },
  { keys = ["end"], command = "cursor_move_end" },

  # vim-like keybindings
  { keys = ["j"], command = "cursor_move_down" },
  { keys = ["k"], command = "cursor_move_up" },
  { keys = ["b"], command = "cursor_move_home" },
  { keys = ["e"], command = "cursor_move_end" },

  { keys = ["w"], command = "show_tasks" },
  { keys = ["escape"], command = "show_tasks" },
]
